name: Build
on: [push, pull_request]
jobs:
  Node:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [20.x]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Packages
        run: npm install

      - name: Build Library
        run: npm run build